# Generated by Django 5.1.3 on 2024-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
