# Generated by Django 5.1.3 on 2024-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_editora_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
