# Generated by Django 5.1.3 on 2024-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_editora_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
